name: Deploy to Heroku

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: 'heroku'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Heroku via git push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/formulo.git
          git push heroku main -f
